### ISSUE TITLE
Make download buttons slightly darker and navbar the same color as them

### ISSUE THREAD

**Issue by 5HT2** [kami-blue/website#15]

**Comment by ghost** [comment]
Comparison of the colour darkened 5%, 10%, 15%, 20%
![](https://i.postimg.cc/4xc2xgCv/darkened.png)

**Comment by 5HT2** [comment]
I'm talking about the white and grey ones xd

**Comment by ghost** [comment]
Those darkened colors **are** the "grey" colour darkened. The button color looks grey because it is on a purple background, but it is actually a greyish-purple.

**Comment by 5HT2** [comment]
Oooh ok. Ty <3

I'll look into it
