### ISSUE TITLE
Haram

### ISSUE THREAD

**Issue by d1snin** [kami-blue/website#47]
FullBright is not in alphabetical order lol
![Screenshot_8](https://user-images.githubusercontent.com/68169685/94043046-fabff680-fdd4-11ea-84fc-97974209b3ab.png)

**Comment by Metacinnabar** [comment]
nice

**Comment by 5HT2** [comment]
the list is autogenerated so idk what's going on there

should be fixed next time I run the command

**Comment by d1snin** [comment]
based
